// Insufficiently Random Values are an application security vulnerability whereby the application generates predictable values in sensitive areas of code that absolutely require strict randomness (unpredictability). As a result it may be possible for an attacker to predict the next value generated by the application to defeat cryptographic routines, access sensitive information, or impersonate another user.
public class UseofInsufficientlyRandomValues {
    protected String newSession() {
        // long now = System.currentTimeMillis();
        SecureRandom rand = new SecureRandom();
        byte bytes[] = new byte[20];
        rand.nextBytes(bytes);
        String cookie = new String(Hex.encodeHex(bytes));
        return cookie;
        // return encode(now);
    }

    // private String encode(long time) {
    // return new String(Long.toString(time));
    // }
}
